### ISSUE TITLE
isFiltered is not defined

### ISSUE THREAD

**Issue by beljand** [nolanlawson/pouchdb-quick-search#58]
I tried to do a simple query, but I only get 
`Object {error: "ReferenceError", name: "ReferenceError", reason: "isFiltered is not defined", message: "isFiltered is not defined", status: 500}`

**Comment by nolanlawson** [comment]
Can you provide a test case to reproduce?

**Comment by AnnamrajuSarvani** [comment]
Hi,
I am using pouchdb on node js with this plugin but not able to search because of the above issue mentioned...

```js
var PouchDB = require('pouchdb');
PouchDB.plugin(require('pouchdb-quick-search'));
var db = new PouchDB('http://127.0.0.1:5984/users');
db.search({
    query: 'maria',
    fields: ['name']
  }).then(function(result) {
    console.log(result,"========")
    res.send(200,result);
    // handle results
  }).catch(function(err) {
    // handle error    
    console.log(err,"========")
    res.send(500,err);
  });
output of the above code is this : {
  "code": "ESOCKETTIMEDOUT",
  "connect": false,
  "status": 500
}
```

Now I checked pouch db server logs and I find :

```
Please double-check your map/reduce function.
ReferenceError: isFiltered is not defined
at evalmachine.<anonymous>:3:9
    at /usr/local/lib/node_modules/pouchdb-server/node_modules/pouchdb-mapreduce/lib/index.js:147:14
    at tryMap (/usr/local/lib/node_modules/pouchdb-server/node_modules/pouchdb-abstract-mapreduce/lib/index.js:166:7)
    at createDocIdsToChangesAndEmits (/usr/local/lib/node_modules/pouchdb-server/node_modules/pouchdb-abstract-mapreduce/lib/index.js:589:13)
    at processBatch (/usr/local/lib/node_modules/pouchdb-server/node_modules/pouchdb-abstract-mapreduce/lib/index.js:572:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

I want to know where I am doing wrong.

**Comment by nolanlawson** [comment]
Thanks for the test case! I don't have time to fix this now, but maybe I will soon. 😅

**Comment by AnnamrajuSarvani** [comment]
Soon?? When can I expect?

**Comment by nolanlawson** [comment]
I'm not actively working on this project, but pull requests are welcome. :)
